# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\andre\Documents\BruinSpace\Rapid\Rapid-Blue-Dawn-Ground-Testing\GSE\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(706, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/MainLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 661, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.port_groupbox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.port_groupbox.setObjectName("port_groupbox")
        self.formLayoutWidget = QtWidgets.QWidget(self.port_groupbox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 19, 661, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelBlue = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelBlue.setObjectName("labelBlue")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelBlue)
        self.bd_port = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bd_port.sizePolicy().hasHeightForWidth())
        self.bd_port.setSizePolicy(sizePolicy)
        self.bd_port.setInputMask("")
        self.bd_port.setText("")
        self.bd_port.setObjectName("bd_port")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bd_port)
        self.labelUmb = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelUmb.setObjectName("labelUmb")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelUmb)
        self.ub_port = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ub_port.sizePolicy().hasHeightForWidth())
        self.ub_port.setSizePolicy(sizePolicy)
        self.ub_port.setObjectName("ub_port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ub_port)
        self.buttonConnect = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonConnect.sizePolicy().hasHeightForWidth())
        self.buttonConnect.setSizePolicy(sizePolicy)
        self.buttonConnect.setDefault(False)
        self.buttonConnect.setFlat(False)
        self.buttonConnect.setObjectName("buttonConnect")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttonConnect)
        self.verticalLayout.addWidget(self.port_groupbox)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 8)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Bruin Space GSE Setup"))
        self.label.setText(_translate("mainWindow", "Project Rapid - Blue Dawn"))
        self.port_groupbox.setTitle(_translate("mainWindow", "Setup"))
        self.labelBlue.setText(_translate("mainWindow", "Blue Dawn Port"))
        self.labelUmb.setText(_translate("mainWindow", "Umbilical Port"))
        self.buttonConnect.setText(_translate("mainWindow", "Connect"))

import resources_rc
