# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\andre\Documents\BruinSpace\Rapid\Rapid-Blue-Dawn-Ground-Testing\GSE\gse\monitorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Monitor(object):
    def setupUi(self, Monitor):
        Monitor.setObjectName("Monitor")
        Monitor.resize(1182, 755)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/MainLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Monitor.setWindowIcon(icon)
        Monitor.setStyleSheet("QFile file(\":/styles.qss\");\n"
"file.open(QFile::ReadOnly | QFile::Text);\n"
"")
        self.verticalLayoutWidget = QtWidgets.QWidget(Monitor)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 1161, 741))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 561, 461))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 8, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 5, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 6, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 8, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 7, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 561, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 8, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 7, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 11, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 9, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 10, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 12, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 3, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 7, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 8, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 4, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 5, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 6, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 9, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 10, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 11, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 12, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setStyleSheet("styles.qss")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Monitor)
        QtCore.QMetaObject.connectSlotsByName(Monitor)

    def retranslateUi(self, Monitor):
        _translate = QtCore.QCoreApplication.translate
        Monitor.setWindowTitle(_translate("Monitor", "Bruin Space GSE Monitor"))
        self.groupBox.setTitle(_translate("Monitor", "Blue Dawn"))
        self.label_18.setText(_translate("Monitor", "Voltage"))
        self.label_16.setText(_translate("Monitor", "Current"))
        self.label_19.setText(_translate("Monitor", "Accel Vector"))
        self.label_17.setText(_translate("Monitor", "Value"))
        self.label_14.setText(_translate("Monitor", "Value"))
        self.label_13.setText(_translate("Monitor", "Timer"))
        self.label_15.setText(_translate("Monitor", "Value"))
        self.label_21.setText(_translate("Monitor", "Ang Vel Vector"))
        self.label_22.setText(_translate("Monitor", "Value"))
        self.label_7.setText(_translate("Monitor", "Value"))
        self.label_9.setText(_translate("Monitor", "Flow Rate"))
        self.label_10.setText(_translate("Monitor", "Spacecraft Time"))
        self.label_8.setText(_translate("Monitor", "MOSFET State"))
        self.label_20.setText(_translate("Monitor", "Mag Vector"))
        self.label_23.setText(_translate("Monitor", "Value"))
        self.label_24.setText(_translate("Monitor", "Value, Value, Value"))
        self.label_26.setText(_translate("Monitor", "Value, Value, Value"))
        self.label_25.setText(_translate("Monitor", "Value, Value, Value"))
        self.groupBox_2.setTitle(_translate("Monitor", "NFF Data"))
        self.label_27.setText(_translate("Monitor", "Accel Vector"))
        self.label_11.setText(_translate("Monitor", "Velocity Vector"))
        self.label_28.setText(_translate("Monitor", "Ang Vel Vector"))
        self.label_12.setText(_translate("Monitor", "Atitude Vector"))
        self.label_30.setText(_translate("Monitor", "RCS warning"))
        self.label_29.setText(_translate("Monitor", "Liftoff Warning"))
        self.label_33.setText(_translate("Monitor", "Landing Warning"))
        self.label_31.setText(_translate("Monitor", "Escape Warning"))
        self.label_32.setText(_translate("Monitor", "Chute Warning"))
        self.label_2.setText(_translate("Monitor", "Altitude"))
        self.label.setText(_translate("Monitor", "Exp Time"))
        self.label_3.setText(_translate("Monitor", "Value"))
        self.label_6.setText(_translate("Monitor", "Value"))
        self.label_5.setText(_translate("Monitor", "Value"))
        self.label_4.setText(_translate("Monitor", "Flight State"))
        self.label_34.setText(_translate("Monitor", "Fault Warning"))
        self.label_35.setText(_translate("Monitor", "Value, Value, Value"))
        self.label_36.setText(_translate("Monitor", "Value"))
        self.label_37.setText(_translate("Monitor", "Value"))
        self.label_38.setText(_translate("Monitor", "Value, Value, Value"))
        self.label_39.setText(_translate("Monitor", "Value, Value, Value"))
        self.label_40.setText(_translate("Monitor", "Value, Value, Value"))
        self.label_41.setText(_translate("Monitor", "Value"))
        self.label_42.setText(_translate("Monitor", "Value"))
        self.label_43.setText(_translate("Monitor", "Value"))
        self.label_44.setText(_translate("Monitor", "Value"))
        self.groupBox_3.setTitle(_translate("Monitor", "Command"))

